### PR TITLE
reset then write hash, fix issue #17

### PR DESCRIPTION
**Pull request by jannson**
please read the issue #17 for more information

### CODE REVIEW

**Comment by TDAbboud** [comment]
Is there any way we can get this merged? This is fixes a pretty serious bug.

**Comment by TDAbboud** [comment]
ping @serialx

**Comment by hzj629206** [comment]
ping @serialx +1

**Comment by corverroos** [comment]
This should do the trick ito workaround until this PR is merged:
```
type h struct {
	hash.Hash
}

func (h) Sum(b []byte) []byte {
	r := md5.Sum(b)
	return r[:]
}

...
// Then use NewWithHash
ring := hashring.NewWithHash(nodes, h{})
```

**Comment by corverroos** [comment]
This should do the trick ito workaround until this PR is merged:
```
type h struct {
	hash.Hash
}

func (h) Sum(b []byte) []byte {
	r := md5.Sum(b)
	return r[:]
}

...
// Then use NewWithHash
ring := hashring.NewWithHash(nodes, h{})
```

**Comment by terorie** [comment]
@serialx Any update? The current implementation is completely broken because of this bug. This PR would fix it.

**Comment by serialx** [comment]
Sorry for the late merge. 🙇

**Pull request merged**
